/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TributesRouteImport } from './routes/tributes'
import { Route as ScholarshipRouteImport } from './routes/scholarship'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegacyRouteImport } from './routes/legacy'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingsIndexRouteImport } from './routes/writings.index'
import { Route as ThemesIndexRouteImport } from './routes/themes.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WritingsSlugRouteImport } from './routes/writings.$slug'
import { Route as ThemesSlugRouteImport } from './routes/themes.$slug'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as ApiRobotsDottxtRouteImport } from './routes/api/robots[.]txt'
import { Route as AdminTributesRouteImport } from './routes/admin.tributes'
import { Route as AdminSubscribersRouteImport } from './routes/admin.subscribers'
import { Route as AdminPublicationsRouteImport } from './routes/admin.publications'
import { Route as AdminArticlesRouteImport } from './routes/admin.articles'
import { Route as ApiPublicAskRouteImport } from './routes/api/public/ask'

const TributesRoute = TributesRouteImport.update({
  id: '/tributes',
  path: '/tributes',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipRoute = ScholarshipRouteImport.update({
  id: '/scholarship',
  path: '/scholarship',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRoute = LegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingsIndexRoute = WritingsIndexRouteImport.update({
  id: '/writings/',
  path: '/writings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesIndexRoute = ThemesIndexRouteImport.update({
  id: '/themes/',
  path: '/themes/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const WritingsSlugRoute = WritingsSlugRouteImport.update({
  id: '/writings/$slug',
  path: '/writings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesSlugRoute = ThemesSlugRouteImport.update({
  id: '/themes/$slug',
  path: '/themes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobotsDottxtRoute = ApiRobotsDottxtRouteImport.update({
  id: '/api/robots.txt',
  path: '/api/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTributesRoute = AdminTributesRouteImport.update({
  id: '/tributes',
  path: '/tributes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubscribersRoute = AdminSubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPublicationsRoute = AdminPublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArticlesRoute = AdminArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicAskRoute = ApiPublicAskRouteImport.update({
  id: '/api/public/ask',
  path: '/api/public/ask',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRoute
  '/legacy': typeof LegacyRoute
  '/login': typeof LoginRoute
  '/scholarship': typeof ScholarshipRoute
  '/tributes': typeof TributesRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/tributes': typeof AdminTributesRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/writings/$slug': typeof WritingsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/themes/': typeof ThemesIndexRoute
  '/writings/': typeof WritingsIndexRoute
  '/api/public/ask': typeof ApiPublicAskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/legacy': typeof LegacyRoute
  '/login': typeof LoginRoute
  '/scholarship': typeof ScholarshipRoute
  '/tributes': typeof TributesRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/tributes': typeof AdminTributesRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/writings/$slug': typeof WritingsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/themes': typeof ThemesIndexRoute
  '/writings': typeof WritingsIndexRoute
  '/api/public/ask': typeof ApiPublicAskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/ask': typeof AskRoute
  '/legacy': typeof LegacyRoute
  '/login': typeof LoginRoute
  '/scholarship': typeof ScholarshipRoute
  '/tributes': typeof TributesRoute
  '/admin/articles': typeof AdminArticlesRoute
  '/admin/publications': typeof AdminPublicationsRoute
  '/admin/subscribers': typeof AdminSubscribersRoute
  '/admin/tributes': typeof AdminTributesRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/writings/$slug': typeof WritingsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/themes/': typeof ThemesIndexRoute
  '/writings/': typeof WritingsIndexRoute
  '/api/public/ask': typeof ApiPublicAskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ask'
    | '/legacy'
    | '/login'
    | '/scholarship'
    | '/tributes'
    | '/admin/articles'
    | '/admin/publications'
    | '/admin/subscribers'
    | '/admin/tributes'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/themes/$slug'
    | '/writings/$slug'
    | '/admin/'
    | '/themes/'
    | '/writings/'
    | '/api/public/ask'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ask'
    | '/legacy'
    | '/login'
    | '/scholarship'
    | '/tributes'
    | '/admin/articles'
    | '/admin/publications'
    | '/admin/subscribers'
    | '/admin/tributes'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/themes/$slug'
    | '/writings/$slug'
    | '/admin'
    | '/themes'
    | '/writings'
    | '/api/public/ask'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ask'
    | '/legacy'
    | '/login'
    | '/scholarship'
    | '/tributes'
    | '/admin/articles'
    | '/admin/publications'
    | '/admin/subscribers'
    | '/admin/tributes'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/themes/$slug'
    | '/writings/$slug'
    | '/admin/'
    | '/themes/'
    | '/writings/'
    | '/api/public/ask'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AskRoute: typeof AskRoute
  LegacyRoute: typeof LegacyRoute
  LoginRoute: typeof LoginRoute
  ScholarshipRoute: typeof ScholarshipRoute
  TributesRoute: typeof TributesRoute
  ApiRobotsDottxtRoute: typeof ApiRobotsDottxtRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  ThemesSlugRoute: typeof ThemesSlugRoute
  WritingsSlugRoute: typeof WritingsSlugRoute
  ThemesIndexRoute: typeof ThemesIndexRoute
  WritingsIndexRoute: typeof WritingsIndexRoute
  ApiPublicAskRoute: typeof ApiPublicAskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tributes': {
      id: '/tributes'
      path: '/tributes'
      fullPath: '/tributes'
      preLoaderRoute: typeof TributesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarship': {
      id: '/scholarship'
      path: '/scholarship'
      fullPath: '/scholarship'
      preLoaderRoute: typeof ScholarshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy': {
      id: '/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writings/': {
      id: '/writings/'
      path: '/writings'
      fullPath: '/writings/'
      preLoaderRoute: typeof WritingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/': {
      id: '/themes/'
      path: '/themes'
      fullPath: '/themes/'
      preLoaderRoute: typeof ThemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/writings/$slug': {
      id: '/writings/$slug'
      path: '/writings/$slug'
      fullPath: '/writings/$slug'
      preLoaderRoute: typeof WritingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/$slug': {
      id: '/themes/$slug'
      path: '/themes/$slug'
      fullPath: '/themes/$slug'
      preLoaderRoute: typeof ThemesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/robots.txt': {
      id: '/api/robots.txt'
      path: '/api/robots.txt'
      fullPath: '/api/robots.txt'
      preLoaderRoute: typeof ApiRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tributes': {
      id: '/admin/tributes'
      path: '/tributes'
      fullPath: '/admin/tributes'
      preLoaderRoute: typeof AdminTributesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subscribers': {
      id: '/admin/subscribers'
      path: '/subscribers'
      fullPath: '/admin/subscribers'
      preLoaderRoute: typeof AdminSubscribersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/publications': {
      id: '/admin/publications'
      path: '/publications'
      fullPath: '/admin/publications'
      preLoaderRoute: typeof AdminPublicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/articles': {
      id: '/admin/articles'
      path: '/articles'
      fullPath: '/admin/articles'
      preLoaderRoute: typeof AdminArticlesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/ask': {
      id: '/api/public/ask'
      path: '/api/public/ask'
      fullPath: '/api/public/ask'
      preLoaderRoute: typeof ApiPublicAskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminArticlesRoute: typeof AdminArticlesRoute
  AdminPublicationsRoute: typeof AdminPublicationsRoute
  AdminSubscribersRoute: typeof AdminSubscribersRoute
  AdminTributesRoute: typeof AdminTributesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArticlesRoute: AdminArticlesRoute,
  AdminPublicationsRoute: AdminPublicationsRoute,
  AdminSubscribersRoute: AdminSubscribersRoute,
  AdminTributesRoute: AdminTributesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AskRoute: AskRoute,
  LegacyRoute: LegacyRoute,
  LoginRoute: LoginRoute,
  ScholarshipRoute: ScholarshipRoute,
  TributesRoute: TributesRoute,
  ApiRobotsDottxtRoute: ApiRobotsDottxtRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  ThemesSlugRoute: ThemesSlugRoute,
  WritingsSlugRoute: WritingsSlugRoute,
  ThemesIndexRoute: ThemesIndexRoute,
  WritingsIndexRoute: WritingsIndexRoute,
  ApiPublicAskRoute: ApiPublicAskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
