/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScholarshipRouteImport } from './routes/scholarship'
import { Route as LegacyRouteImport } from './routes/legacy'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WritingsIndexRouteImport } from './routes/writings.index'
import { Route as ThemesIndexRouteImport } from './routes/themes.index'
import { Route as WritingsSlugRouteImport } from './routes/writings.$slug'
import { Route as ThemesSlugRouteImport } from './routes/themes.$slug'
import { Route as ApiSitemapDotxmlRouteImport } from './routes/api/sitemap[.]xml'
import { Route as ApiRobotsDottxtRouteImport } from './routes/api/robots[.]txt'
import { Route as ApiPublicAskRouteImport } from './routes/api/public/ask'

const ScholarshipRoute = ScholarshipRouteImport.update({
  id: '/scholarship',
  path: '/scholarship',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRoute = LegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingsIndexRoute = WritingsIndexRouteImport.update({
  id: '/writings/',
  path: '/writings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesIndexRoute = ThemesIndexRouteImport.update({
  id: '/themes/',
  path: '/themes/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingsSlugRoute = WritingsSlugRouteImport.update({
  id: '/writings/$slug',
  path: '/writings/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesSlugRoute = ThemesSlugRouteImport.update({
  id: '/themes/$slug',
  path: '/themes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSitemapDotxmlRoute = ApiSitemapDotxmlRouteImport.update({
  id: '/api/sitemap.xml',
  path: '/api/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRobotsDottxtRoute = ApiRobotsDottxtRouteImport.update({
  id: '/api/robots.txt',
  path: '/api/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAskRoute = ApiPublicAskRouteImport.update({
  id: '/api/public/ask',
  path: '/api/public/ask',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/legacy': typeof LegacyRoute
  '/scholarship': typeof ScholarshipRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/writings/$slug': typeof WritingsSlugRoute
  '/themes/': typeof ThemesIndexRoute
  '/writings/': typeof WritingsIndexRoute
  '/api/public/ask': typeof ApiPublicAskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/legacy': typeof LegacyRoute
  '/scholarship': typeof ScholarshipRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/writings/$slug': typeof WritingsSlugRoute
  '/themes': typeof ThemesIndexRoute
  '/writings': typeof WritingsIndexRoute
  '/api/public/ask': typeof ApiPublicAskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ask': typeof AskRoute
  '/legacy': typeof LegacyRoute
  '/scholarship': typeof ScholarshipRoute
  '/api/robots.txt': typeof ApiRobotsDottxtRoute
  '/api/sitemap.xml': typeof ApiSitemapDotxmlRoute
  '/themes/$slug': typeof ThemesSlugRoute
  '/writings/$slug': typeof WritingsSlugRoute
  '/themes/': typeof ThemesIndexRoute
  '/writings/': typeof WritingsIndexRoute
  '/api/public/ask': typeof ApiPublicAskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ask'
    | '/legacy'
    | '/scholarship'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/themes/$slug'
    | '/writings/$slug'
    | '/themes/'
    | '/writings/'
    | '/api/public/ask'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ask'
    | '/legacy'
    | '/scholarship'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/themes/$slug'
    | '/writings/$slug'
    | '/themes'
    | '/writings'
    | '/api/public/ask'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ask'
    | '/legacy'
    | '/scholarship'
    | '/api/robots.txt'
    | '/api/sitemap.xml'
    | '/themes/$slug'
    | '/writings/$slug'
    | '/themes/'
    | '/writings/'
    | '/api/public/ask'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AskRoute: typeof AskRoute
  LegacyRoute: typeof LegacyRoute
  ScholarshipRoute: typeof ScholarshipRoute
  ApiRobotsDottxtRoute: typeof ApiRobotsDottxtRoute
  ApiSitemapDotxmlRoute: typeof ApiSitemapDotxmlRoute
  ThemesSlugRoute: typeof ThemesSlugRoute
  WritingsSlugRoute: typeof WritingsSlugRoute
  ThemesIndexRoute: typeof ThemesIndexRoute
  WritingsIndexRoute: typeof WritingsIndexRoute
  ApiPublicAskRoute: typeof ApiPublicAskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scholarship': {
      id: '/scholarship'
      path: '/scholarship'
      fullPath: '/scholarship'
      preLoaderRoute: typeof ScholarshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy': {
      id: '/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writings/': {
      id: '/writings/'
      path: '/writings'
      fullPath: '/writings/'
      preLoaderRoute: typeof WritingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/': {
      id: '/themes/'
      path: '/themes'
      fullPath: '/themes/'
      preLoaderRoute: typeof ThemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writings/$slug': {
      id: '/writings/$slug'
      path: '/writings/$slug'
      fullPath: '/writings/$slug'
      preLoaderRoute: typeof WritingsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes/$slug': {
      id: '/themes/$slug'
      path: '/themes/$slug'
      fullPath: '/themes/$slug'
      preLoaderRoute: typeof ThemesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sitemap.xml': {
      id: '/api/sitemap.xml'
      path: '/api/sitemap.xml'
      fullPath: '/api/sitemap.xml'
      preLoaderRoute: typeof ApiSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/robots.txt': {
      id: '/api/robots.txt'
      path: '/api/robots.txt'
      fullPath: '/api/robots.txt'
      preLoaderRoute: typeof ApiRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ask': {
      id: '/api/public/ask'
      path: '/api/public/ask'
      fullPath: '/api/public/ask'
      preLoaderRoute: typeof ApiPublicAskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AskRoute: AskRoute,
  LegacyRoute: LegacyRoute,
  ScholarshipRoute: ScholarshipRoute,
  ApiRobotsDottxtRoute: ApiRobotsDottxtRoute,
  ApiSitemapDotxmlRoute: ApiSitemapDotxmlRoute,
  ThemesSlugRoute: ThemesSlugRoute,
  WritingsSlugRoute: WritingsSlugRoute,
  ThemesIndexRoute: ThemesIndexRoute,
  WritingsIndexRoute: WritingsIndexRoute,
  ApiPublicAskRoute: ApiPublicAskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
